outroot: "./example/out"
LC_TBIN: 10
LC_PLOT_YMIN: 0.0
LC_PLOT_YMAX: 1000.0
LC_FIT_XMIN: 1.0
LCHIST_NBIN: 200
DELTAT_TBIN: 0.004
DELTAT_PLOT_XMAX: 0.4
DELTATRIGGERCOUNT_PLOT_XMIN: -0.5
DELTATRIGGERCOUNT_PLOT_XMAX: 29.5
SPEC_PLOT_XMIN: -0.5
SPEC_PLOT_XMAX: 511.5
